# Generated by Django 5.0.6 on 2024-05-14 09:55

import Books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, validators=[Books.models.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=100, validators=[Books.models.validate_alpha]),
        ),
    ]
